version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ../db/postgres/backup:/var/lib/postgresql/data

  mongo:
    image : mongo:latest
    container_name: mongodb
    restart: always
    working_dir: /backup
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_NON_ROOT_USERNAME: user
      MONGO_NON_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
    volumes:
      - ../db/mongodb/backup:/backup
